sudo: false
language: node_js
os:
  - linux
  - osx
node_js:
  - "8"
before_install:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest'
  - npm install -g greenkeeper-lockfile@1
install:
  - npm install
before_script: greenkeeper-lockfile-update
script:
  - npm start ci
after_script: greenkeeper-lockfile-upload
